services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-net
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-net
    image: stuberlo/zombiebackend
  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - app-net
    environment:
      - ORIGIN=http://proxy:80
    image: stuberlo/zombiefrontend

networks:
  app-net:
    driver: bridge
